export const INFO_TYPE = {
	BANNER: 'BANNER',
	CONTENT: 'CONTENT',
	SINGLE_PRODUCT: 'SINGLE_PRODUCT',
	BEST_SELLER_PRODUCTS: 'BEST_SELLER_PRODUCTS',
	NEW_PRODUCTS: 'BEST_SELLER_PRODUCTS',
	CATEGORY: 'CATEGORY'
}
